baseURL = 'https://majana.netlify.app/'
languageCode = 'en-us'
title = 'Majana'
theme = 'PaperMod'

[params]
  description = "Majana: Elevate Your Business with Strategic Marketing"
  images = ["https://majana.netlify.app/images/branding.jpg"]
  ShowReadingTime = false
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  disableSummary = false
  ShowToc = true
  TocOpen = false
  TocTitle = "Table of Contents"
  ShowTags = true
  ShowCategory = true
  defaultTheme = "auto"
  homeInfoMode = "true"

[params.profileMode]
  enabled = true
  title = "Majana: Elevate Your Business"
  subtitle = "Strategic Marketing for Business Growth"
  imageUrl = "https://majana.netlify.app/images/branding.jpg"
  imageTitle = "Majana Logo"
  imageWidth = 120
  imageHeight = 120

[[params.profileMode.buttons]]
  name = "Archive"
  url = "/archive"

[[params.profileMode.buttons]]
  name = "Github"
  url = "https://github.com/Moshe-ship"

[social]
  github = "https://github.com/Moshe-ship"
  linkedin = "https://www.linkedin.com/in/yourprofile"
  twitter = "https://twitter.com/yourprofile"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

[[menu.main]]
  name = "Services"
  url = "/services/"
  weight = 3

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 4

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
