baseURL = 'https://majana.netlify.app/'
languageCode = 'en-us'
title = 'Majana'
theme = 'PaperMod'

[params]
  description = "Majana: Elevate Your Business with Strategic Marketing"
  images = ["https://majana.netlify.app/images/branding.jpg"]
  ShowReadingTime = false
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = false  # Hide breadcrumbs
  disableSummary = false
  ShowToc = false  # Hide Table of Contents
  TocOpen = false
  TocTitle = "Table of Contents"
  ShowTags = true
  ShowCategory = true
  defaultTheme = "auto"
  customCSS = []

[social]
  github = "https://github.com/Moshe-ship"
  linkedin = "https://www.linkedin.com/in/yourprofile"
  twitter = "https://twitter.com/yourprofile"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

[[menu.main]]
  name = "Services"
  url = "/services/"
  weight = 3

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 4

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
